secretGenerator:
- name: gnoweb-env
  namespace: gno
  options:
    disableNameSuffixHash: true
  literals:
  - CHAIN_ID=dev
  - FAUCET_URL=http://gnofaucet:5050
  - RPC_REMOTE=http://rpc.gnoland.tech
  - CAPTCHA_SITE_KEY=apublic_captcha
