secretGenerator:
- name: gnoweb-env
  namespace: gno
  literals:
  - CHAIN_ID=dev
  - RPC_REMOTE=https://rpc.test4.gno.land
  # Avoids that name of secret is suffixed with random padding numbers
  options:
    disableNameSuffixHash: true