apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: test5-gnocore-helm
profiles:
  - name: test5-dev
    manifests:
      helm:
        releases:
        ## RPC
        - &helmInstance
          name: rpc-01
          chartPath: ../../core/helm
          valuesFiles:
            - ../../core/test5/rpc-01/values.yaml
        ## Sentries
        - <<: *helmInstance
          name: sentry-01
          valuesFiles:
            - ../../core/test5/sentry-01/values.yaml
        ## Validators
        - <<: *helmInstance
          name: val-01
          valuesFiles:
            - ../../core/test5/val-01/values.yaml
  - name: test5-eks
    manifests:
      helm:
        releases:
        ## RPC
        - <<: *helmInstance
          name: rpc-01
          valuesFiles:
            - ../../core/test5/rpc-01/eks-values.yaml
        ## Sentries
        - <<: *helmInstance
          name: sentry-01
          valuesFiles:
            - ../../core/test5/sentry-01/eks-values.yaml
        ## Validators
        - <<: *helmInstance
          name: val-01
          valuesFiles:
            - ../../core/test5/val-01/eks-values.yaml
deploy:
  helm: {}
