apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gnocore
manifests:
  rawYaml:
    - ../../cluster/namespaces/core.yaml
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          ## Gnoland
          ### RPC
          - ../../core/gnoland/rpc
          ### Indexer
          - ../../core/indexer
          ### Gnofaucet
          - ../../core/gnofaucet
          ### Gnoweb
          - ../../core/gnoweb
          ### Validator 1
          - ../../core/gnoland/validator
  - name: eks-dev
    manifests:
      kustomize:
        paths:
          ## AWS Storage Class + EKS Storage
          - ../../aws-eks/storage
          ## Gnoland overlays
          - ../../core/overlays/eks/gnoland/rpc
          - ../../core/overlays/eks/indexer
          - ../../core/overlays/eks/gnofaucet
          - ../../core/overlays/eks/gnoweb

deploy:
  kubectl: {}
