apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gnocore
manifests:
  rawYaml:
    - ../../cluster/namespaces/core.yaml
profiles:
  - name: dev
    manifests:
      rawYaml:
        - ../../cluster/namespaces/core.yaml
      kustomize:
        paths:
          ## Gnoland
          ### RPC
          - ../../core/gnoland/rpc
          # ### Indexer
          - ../../core/indexer
          ### Gnofaucet
          - ../../core/gnofaucet
          ### Gnoweb
          - ../../core/gnoweb
  - name: eks-dev
    manifests:
      rawYaml:
        - ../../cluster/namespaces/core.yaml
        ## AWS Storage Class
        - ../../aws-eks/storage/storage-class.yaml
      kustomize:
        paths:
          ## EKS Storage
          - ../../aws-eks/storage/csi
          ## Gnoland overlays
          - ../../core/overlays/eks/gnoland/rpc
          - ../../core/overlays/eks/indexer
          - ../../core/overlays/eks/gnofaucet
          - ../../core/overlays/eks/gnoweb

deploy:
  kubectl: {}
