apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: test5-gnocore
manifests:
  rawYaml:
    - ../../cluster/namespaces/core.yaml
profiles:
  - name: test5-dev
    manifests:
      kustomize:
        paths:
          ## Gnoland
          ### RPC
          - ../../core/test5/overlays/rpc/
          # ### Indexer
          - ../../core/indexer
          ### Gnofaucet
          - ../../core/gnofaucet
          ### Gnoweb
          - ../../core/gnoweb
          ## Validators
          - ../../core/test5/val-01
  - name: test5-eks
    manifests:
      kustomize:
        paths:
          ## AWS Storage Class + EKS Storage
          - ../../aws-eks/storage
          ## Gnoland overlays
          # - ../../core/test5/overlays/eks/gnoland/rpc
          - ../../core/test5/overlays/eks/indexer
          - ../../core/test5/overlays/eks/gnofaucet
          - ../../core/test5/overlays/eks/gnoweb
          # TODO: move into general
          - ../../core/test5/overlays/rpc/
          - ../../core/test5/val-01
deploy:
  kubectl: {}
