apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: monitoring
manifests:
  rawYaml:
    - ../../cluster/namespaces/monitoring.yaml
    # Node exporter
    - ../../monitoring/node-exporter/daemonset/*.yaml
profiles:
  - name: dev
    manifests:
      kustomize:
        paths: &dev_monitoring_deploys
          # Prometheus
          - ../../monitoring/prometheus
          # Loki
          - ../../monitoring/loki
          # Vector
          - ../../monitoring/vector
          # Grafana
          - ../../monitoring/grafana
  - name: eks-dev
    manifests:
      kustomize:
        paths: &eks_monitoring_deploys
          ## AWS Storage Class + EKS Storage
          - ../../aws-eks/storage
          # Not overridden
          # Prometheus
          - ../../monitoring/prometheus
          # Vector
          - ../../monitoring/vector
          ### Monitoring Overlays
          - ../../monitoring/overlays/eks/loki
          - ../../monitoring/overlays/eks/grafana
  ## Test5
  - name: test5-dev
    manifests:
      kustomize:
        paths: *dev_monitoring_deploys
  - name: test5-eks
    manifests:
      kustomize:
        paths: 
          - *eks_monitoring_deploys
          - ../../monitoring/overlays/eks/grafana

deploy:
  kubectl: {}
