apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: monitoring
manifests:
  rawYaml:
    - ../../cluster/namespaces/monitoring.yaml
    # Node exporter
    - ../../monitoring/node-exporter/daemonset/*.yaml
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          # Prometheus
          - ../../monitoring/prometheus
          # Loki
          - ../../monitoring/loki
          # Vector
          - ../../monitoring/vector
          # Grafana
          - ../../monitoring/grafana
  - name: eks-dev
    manifests:
      rawYaml:
      #   - ../../cluster/namespaces/monitoring.yaml
        ## AWS Storage Class
        - ../../aws-eks/storage/storage-class.yaml
      kustomize:
        paths:
          ## EKS Storage
          - ../../aws-eks/storage/csi
          ### Monitoring Overlays
          - ../../monitoring/overlays/eks/loki
          - ../../monitoring/overlays/eks/grafana

deploy:
  kubectl: {}
