apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: monitoring
manifests:
  rawYaml:
    - ../../cluster/namespaces/monitoring.yaml
    ## Node exporter - Kustomization version also available,
    ## but here to reduce repetitions in multiple skaffold profiles
    - ../../monitoring/node-exporter/daemonset/*.yaml
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          ## Otel
          - ../../monitoring/otel
          ## Prometheus
          - ../../monitoring/prometheus
          ## Vector
          - ../../monitoring/vector
          ## Loki
          - ../../monitoring/loki
          ## Grafana
          - ../../monitoring/grafana
  - name: eks-dev
    manifests:
      kustomize:
        paths:
          ## AWS Storage Class + EKS Storage
          - ../../aws-eks/storage
          # Not overridden
          ## Otel
          - ../../monitoring/otel
          ## Prometheus
          - ../../monitoring/prometheus
          ## Vector
          - ../../monitoring/vector
          ## Monitoring Overlays
          - ../../monitoring/overlays/eks/loki
          - ../../monitoring/overlays/eks/grafana

deploy:
  kubectl: {}
