apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: monitoring
manifests:
  rawYaml:
    - ../../cluster/namespaces/monitoring.yaml
    # Prometheus
    - ../../monitoring/prometheus/prometheus-rbac.yaml
    - ../../monitoring/prometheus/deploys/*.yaml
    # - ../../monitoring/prometheus/ingress/*.yaml
    # Node exporter
    - ../../monitoring/node-exporter/daemonset/*.yaml
    # Loki
    - ../../monitoring/loki/storage/*.yaml
    - ../../monitoring/loki/deploys/*.yaml
    # Vector
    - ../../monitoring/vector/vector-rbac.yaml
    - ../../monitoring/vector/daemonset/*.yaml
    - ../../monitoring/vector/deploys/*.yaml
    # Grafana
    - ../../monitoring/grafana/storage/*.yaml
    - ../../monitoring/grafana/deploys/*.yaml
    - ../../monitoring/grafana/ingress/*.yaml
  kustomize:
    paths:
      - ../../monitoring/prometheus/configmaps
      - ../../monitoring/loki/configmaps
      - ../../monitoring/vector/configmaps
      - ../../monitoring/grafana/configmaps
      # - ../../monitoring/grafana/secrets

deploy:
  kubectl: {}
