apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: traefik-setup
profiles:
  - name: dev
    manifests:
      kustomize:
        paths: &dev_traefik_deploys
          - ../../traefik/ingress-route/
  - name: eks-dev
    manifests:
      kustomize:
        paths: &eks_traefik_deploys
          - ../../traefik/overlays/eks

deploy:
  kubectl: {}
