apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../gnoweb/

patches:
# fix endpoint ingress
- patch: |- 
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: gnoweb-ingress
      namespace: gno
    spec:
      routes:
      - match: Host(`gnoweb.k8s.gnoteam.com`)
        kind: Rule
        services:
        - name: gnoweb
          namespace: gno
          port: gnoweb-port
