apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../overlays/eks/indexer/
- tx-indexer-tls-ingress-eks.yaml

patches:
- patch: |-
    kind: IngressRoute
    apiVersion: traefik.io/v1alpha1
    metadata:
      name: tx-indexer-ingress
      namespace: gno
    spec:
      entryPoints:
        - web
      routes:
      - match: Host(`indexer.test5.gnoteam.com`) || Host(`indexer.test5.gno.land`)
        kind: Rule
        services:
        - name: tx-indexer
          namespace: gno
          port: tx-indexer-port

- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: indexer-pv-claim
      namespace: gno
    spec:
      storageClassName: eks-ebs-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
