apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../overlays/eks/indexer/
- tx-indexer-tls-ingress-eks.yaml

patches:
- patch: |-
    kind: IngressRoute
    apiVersion: traefik.io/v1alpha1
    metadata:
      name: tx-indexer-ingress
      namespace: gno
    spec:
      entryPoints:
        - web
      routes:
      - match: Host(`indexer.test5.gnoteam.com`)
        kind: Rule
        services:
        - name: tx-indexer
          namespace: gno
          port: tx-indexer-port
