# Gnoland Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gno-val-pv-volume
  namespace: gno
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/gnoland/validator/1/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gno-val-pv-claim
  namespace: gno
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
