services:
  traefik:
    image: "traefik:v2.11"
    command:
      - "--api.insecure=true"
      - "--entrypoints.traefik.address=:8080"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      # - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=security@allinbits.com"
      - "--certificatesresolvers.le.acme.storage=/etc/traefik/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - "./traefik:/etc/traefik"

  gnoland:
    image: "ghcr.io/gnolang/gno/gnoland:master"
    command: ["start", "--genesis=/gnoroot/gnoland-data/genesis.json"]
    ports:
      - 26656:26656
      - 127.0.0.1:26657:26657
    volumes:
      - ./gnoland-data:/gnoroot/gnoland-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gnoland-test4-rpc.rule=Host(`rpc.test4.gno.land`)"
      - "traefik.http.routers.gnoland-test4-rpc.entrypoints=web,websecure"
      - "traefik.http.routers.gnoland-test4-rpc.tls.certresolver=le"
      - "traefik.http.services.gnoland-test4-rpc-service.loadbalancer.server.port=26657"
