apiVersion: batch/v1
kind: Job
metadata:
  name: supernova
  namespace: gno
spec:
  template:
    metadata:
      name: supernova
    spec:
      containers:
      - name: supernova
        image: ghcr.io/gnolang/supernova
        args: [
          "-sub-accounts","1",
          "-transactions","100",
          "-url","http://gnoland:26657",
          "-mnemonic", "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast"
        ]
      restartPolicy: Never
