apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
  - name: grafana-port
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: grafana
        image: grafana/grafana:10.4.2
        imagePullPolicy: IfNotPresent
        env:
        # - name: GF_SECURITY_ADMIN_PASSWORD__FILE
        #   value: "/run/secrets/grafana-sec"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        volumeMounts:
        - name: grafana-vol
          mountPath: /var/lib/grafana
        # - name: grafana-secret
        #   mountPath: /run/secrets/grafana-sec
        #   subPath: grafana.ini
        - name: grafana-dashboard
          mountPath: /etc/grafana/provisioning
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana-vol
        persistentVolumeClaim:
          claimName: grafana-pv-claim
      # - name: grafana-secret
      #   secret:
      #     secretName: grafana-sec
      - name: grafana-dashboard
        configMap:
          name: dashboard-config
          items:
          - key: datasource.yaml
            path: datasources/datasource.yaml
          - key: dashboard.yaml
            path: dashboards/dashboard.yaml
          - key: node-monitoring.json
            path: dashboards/node-monitoring.json
          - key: container-monitoring.json
            path: dashboards/container-monitoring.json
          - key: container-monitoring.json
            path: dashboards/container-monitoring.json
          - key: validators-logs.json
            path: dashboards/validators-logs.json
