apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnoweb
  namespace: gno
spec:
  replicas: 1
  selector:
    matchLabels:
      gno.service: gnoweb
  template:
    metadata:
      labels:
        gno.service: gnoweb
    spec:
      containers:
      - name: gnoweb
        image: ghcr.io/gnolang/gno/gnoweb:master
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: gnoweb-env
        args:
          - --bind=0.0.0.0:8888
          - --remote=http://gnoland-rpc:26657
          - --faucet-url=$(FAUCET_URL)
          - --with-analytics
          - --chainid=$(CHAIN_ID)
          - --help-remote=$(RPC_REMOTE)
