apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   traefik.enable: "true"
  #   traefik.http.routers.gnoweb.entrypoints: web,websecure
  #   traefik.http.routers.gnoweb.rule: Host(`test4.gno.land`) || Host(`test4.gnoteam.com`)
  #   traefik.http.routers.gnoweb.service: gnoweb
  #   traefik.http.routers.gnoweb.tls: "true"
  #   traefik.http.routers.gnoweb.tls.certresolver: le
  #   traefik.http.services.gnoweb.loadbalancer.server.port: "8888"
  name: gnoweb
  namespace: gno
spec:
  replicas: 1
  selector:
    matchLabels:
      gno.service: gnoweb
  template:
    metadata:
      labels:
        gno.service: gnoweb
    spec:
      containers:
      - name: gnoweb
        image: ghcr.io/gnolang/gno/gnoweb:master
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: gnoweb-env
        args:
            - --bind=0.0.0.0:8888
            - --remote=http://gnoland:26657
            - --faucet-url=http://gnofaucet:5050
            - --captcha-site=
            - --with-analytics
            - --help-chainid=$(CHAIN_ID)
            - --help-remote=$(RPC_REMOTE)
