apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmaps/
- storage/gnoland-pv.yaml
- deploys/gnoland-deploy.yaml
- deploys/gnoland-svc.yaml
- ingress/gnoland-ingress.yaml
