apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../configmap-shared
- configmaps/
- storage/gnorpc-pv.yaml
- deploys/gnorpc-deploy.yaml
- deploys/gnorpc-svc.yaml
- ingress/gnorpc-ingress.yaml
