
app:
  name: gnocore-val-06
  role: validator

storage:
  capacity: 120Gi
  class: eks-ebs-storage-tagged

svc:
  name: gnocore-val-svc-06

ingress:
  enabled: false

placement:
  tolerations:
    enabled: true
  resources: # saturate resources
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
