# Inspired by k8s/core/gnoland/rpc/deploys/gnorpc-deploy.yaml for generating genesis file 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-file-server
  namespace: gno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genesis-file-server
  template:
    metadata:
      labels:
        app: genesis-file-server
    spec:
      initContainers:
      - name: init-genesis
        image: busybox
        command:
        - sh
        - -c
        - |
          cp /opt/gnoland/genesis.json /opt/genesis/genesis.json
        volumeMounts:
        - name: genesis-shared
          mountPath: /opt/genesis
        - name: gnoland-genesis
          mountPath: /opt/gnoland

      - name: init-genesis-txs
        image: ghcr.io/gnolang/gno/gnocontribs:master
        command:
        - gnogenesis
        - txs
        - add
        - packages
        - /gnoroot/examples/gno.land
        - -genesis-path
        - /opt/genesis/genesis.json
        volumeMounts:
        - name: genesis-shared
          mountPath: /opt/genesis
      - name: init-genesis-balance
        image: ghcr.io/gnolang/gno/gnocontribs:master
        command:
        - gnogenesis
        - balances
        - add
        - -balance-sheet
        - /gnoroot/gno.land/genesis/genesis_balances.txt
        - -genesis-path
        - /opt/genesis/genesis.json
        volumeMounts:
        - name: genesis-shared
          mountPath: /opt/genesis
      containers:
      - name: genesis-server
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: genesis-shared
          mountPath: /usr/share/nginx/html
      volumes:
      - name: genesis-shared
        emptyDir:
          sizeLimit: 20Mi
      - name: gnoland-genesis
        configMap:
          name: gno-genesis
---
apiVersion: v1
kind: Service
metadata:
  name: genesis-svc
  namespace: gno
spec:
  type: ClusterIP
  selector:
    app: genesis-file-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
