configMapGenerator:
- name: dashboard-config
  namespace: monitoring
  options:
    disableNameSuffixHash: true
  files:
  - dashboard.json=grafana/dashboards/gno-dashboard.json
  - dashboard.yaml=grafana/dashboards/gno-dashboard.yaml
  - datasource.yaml=grafana/datasources/json-datasource.yaml
