configMapGenerator:
- name: dashboard-config
  namespace: monitoring
  options:
    disableNameSuffixHash: true  
  files:
  - datasource.yaml=datasources/datasource.yaml
  - dashboard.yaml=dashboards/dashboard.yaml
  - node-monitoring.json=dashboards/node-monitoring.json
  - container-monitoring.json=dashboards/container-monitoring.json
  - validators-logs.json=dashboards/validators-logs.json
  - gno-otel-dashboards.json=dashboards/gno-otel-dashboards.json
