apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../monitoring/overlays/eks/grafana/
- grafana-tls-ingress-eks.yaml

patches:
- patch: |-
    kind: IngressRoute
    apiVersion: traefik.io/v1alpha1
    metadata:
      name: grafana-ingress
      namespace: monitoring
    spec:
      entryPoints:
        - web
      routes:
      - match: Host(`o11y.test5.gnoteam.com`) || Host(`o11y.test5.gno.land`)
        kind: Rule
        services:
        - name: grafana
          namespace: monitoring
          port: grafana-port
