apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../monitoring/overlays/eks/loki/

patches:
- patch: |-
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: loki
      namespace: monitoring
    spec:
      spec:
        tolerations:
        - key: "type"
          operator: "Equal"
          value: "validator"
          effect: "NoSchedule"
