apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: monitoring-test5
requires:
  - path: ../../../../cluster/skaffold/monitoring-skaffold.yaml
    activeProfiles:
    - name: test5-dev
      activatedBy: [test5-dev]
    - name: test5-eks
      activatedBy: [test5-eks]
profiles:
  - name: test5-dev
  - name: test5-eks
    manifests:
      kustomize:
        paths:
        - ../../overlays/eks/grafana

deploy:
  kubectl: {}
