kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: gnofaucet-ingress-tls
  namespace: gno
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gnofaucet.test5.gnoteam.com`) || Host (`faucet-api.test5.gno.land`)
    kind: Rule
    services:
    - name: gnofaucet
      namespace: gno
      port: gnofaucet-port
  tls:
    certResolver: gnoresolver
