apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../overlays/eks/gnofaucet/
- gnofaucet-tls-ingress-eks.yaml

patches:
- patch: |-
    kind: IngressRoute
    apiVersion: traefik.io/v1alpha1
    metadata:
      name: gnofaucet-ingress
      namespace: gno
    spec:
      entryPoints:
        - web
      routes:
      - match: Host(`gnofaucet.test5.gnoteam.com`)
        kind: Rule
        services:
        - name: gnofaucet
          namespace: gno
          port: gnofaucet-port

secretGenerator:
- name: gnofaucet-env
  namespace: gno
  behavior: replace
  options:
    disableNameSuffixHash: true
  envs:
    - secrets/test5.eks.gnofaucet.ini
