app:
  name: gnocore-rpc-02
  role: validator
  type: rpc

storage:
  capacity: 120Gi
  class: eks-ebs-storage

svc:
  name: gnoland-rpc-alt

ingress:
  enabled: true
  tls: true
  rule:
    host: Host(`rpc-02.test6.gnoteam.com`) || Host(`rpc2.test6.gno.land`)

placement:
  tolerations:
    enabled: true
  resources: # saturate resources
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

gnoland:
  config:
    p2p:
      # Sentry1, Sentry2
      persistent_peers: "g1s0x78pl3c2xv2n7hp33lh4jkyqvhg5hlx6huh7@gnocore-sentry-svc-01:26656,g1jeta40dllwtrh293498hq0dh0cr3u4gw77h5rc@gnocore-sentry-svc-02:26656"
