apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gnocluster
requires:
  - path: cluster/skaffold/traefik-skaffold.yaml
  - path: cluster/skaffold/gnocore-skaffold.yaml
  - path: cluster/skaffold/monitoring-skaffold.yaml
deploy:
  kubectl: {}
