apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gnocluster
requires:
  - path: cluster/skaffold/traefik-skaffold.yaml
  - path: cluster/skaffold/gnocore-skaffold.yaml
    activeProfiles: &kubeProfiles
    - name: dev
      activatedBy: [dev]
    - name: eks-dev
      activatedBy: [eks-dev]
  - path: cluster/skaffold/monitoring-skaffold.yaml
    activeProfiles: *kubeProfiles
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - kubeContext: kind-gnolive
  - name: eks-dev
    activation:
      - kubeContext: arn:aws:eks:eu-west-1:600627336512:cluster/test4b-cluster
    manifests:
      rawYaml:
        ## AWS Storage Class
        - aws-eks/storage/storage-class.yaml
      kustomize:
        paths:
          - traefik/overlays/eks
          ## EKS Storage
          - ../../aws-eks/storage/csi
