
app:
  name: gnocore-val-02
  role: validator

storage:
  capacity: 120Gi
  class: eks-ebs-storage

svc:
  name: gnocore-val-svc-02

ingress:
  enabled: false

placement:
  tolerations:
    enabled: true
  resources: # saturate resources
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

gnoland:
  config:
    persistent_peers: "g16384atcuf6ew3ufpwtvhymwfyl2aw390aq8jtt@gnocore-sentry-svc-01:26656,g1ty443uhf6qr2n0gv3dkemr4slt96e5hnmx90qh@gnocore-sentry-svc-02:26656,g19x2gsyn02fldtq44dpgtcq2dq28kszlf5jn2es@gnocore-sentry-svc-03:26656"
