
app:
  name: gno-sentry-03
  role: validator

storage:
  capacity: 120Gi
  class: eks-ebs-storage

svc:
  name: gno-sentry-svc-03

ingress:
  enabled: true
  port: p2p-internal
  tls: true
  rule:
    host: Host(`gno-core-sen-03.test5.gnoteam.com`)

placement:
  tolerations:
    enabled: true
  resources: # saturate resources
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

