app:
  name: gno-val-01
  role: validator
  initEnv: dev

storage:
  capacity: 1Gi # 120Gi
  local:
    path: /opt/gnoland/validator/1/data

svc:
  name: gno-val-svc-01

ingress:
  enabled: false
  rule:
    host: Host(`sentry-01.gnoland.tech`)

placement:
  tolerations:
    enabled: false

### Globals ###
global:
  binaryVersion: master
