apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- snapshotter-rbac.yaml
- snapshotter-cronjob.yaml

secretGenerator:
- name: snapshotter-env
  namespace: gno
  options:
    disableNameSuffixHash: true
  envs:
    - secrets/.env
