apiVersion: v1
kind: Service
metadata:
  name: otel-svc
  namespace: monitoring
spec:
  selector:
    app: otel-run
  ports:
    - port: 4317
      targetPort: otlp-http
    - port: 8889
      targetPort: 8889

