
data_dir: /vector-data-dir
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false
sources:
  kubernetes_logs:
    type: kubernetes_logs
    extra_field_selector: "metadata.namespace!=kube-system"
  vector_logs:
    type: internal_logs  
  
  host_metrics:
    filesystem:
      devices:
        excludes: [binfmt_misc]
      filesystems:
        excludes: [binfmt_misc]
      mountpoints:
        excludes: ["*/proc/sys/fs/binfmt_misc"]
    type: host_metrics
  internal_metrics:
    type: internal_metrics

sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs: [host_metrics, internal_metrics]
    address: 0.0.0.0:9090

  loki_vectorlogs:
    type: loki
    inputs: [kubernetes_logs]
    encoding:
      codec: "json"
    endpoint: "http://loki-svc:3100"
    labels:
      logsource: kube