kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: prom-stripprefix
  namespace: monitoring
spec:
  stripPrefix:
    prefixes:
      - /prom
---
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: prom-replaceprefix
  namespace: monitoring
spec:
  replacePathRegex:
    regex: ^/prom/(.*)
    replacement: /$1
---
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: prometheus-ingress
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/prom`) || !PathPrefix(`/gno`)
    kind: Rule
    services:
    - name: prometheus-svc
      namespace: monitoring
      port: 8080
    middlewares:
    - name: prom-stripprefix
      namespace: monitoring
    - name: prom-replaceprefix
      namespace: monitoring
---
