apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gnocluster
requires:
  # Traefik
  - path: ../../cluster/skaffold/traefik-skaffold.yaml
    activeProfiles: &kubeProfiles
    - name: test6-dev
      activatedBy: [test6-dev]
    - name: test6-eks
      activatedBy: [test6-eks]

  # Gnoland
  - path: ./cluster/skaffold/gnocore-test6-skaffold.yaml
    activeProfiles: *kubeProfiles

  - path: ./cluster/skaffold/gnocore-test6-helm-skaffold.yaml
    activeProfiles: *kubeProfiles

  # Monitoring
  ## FIXME: attempt to reuse basic file 
  - path: ../../cluster/skaffold/monitoring-skaffold.yaml
    activeProfiles:
    - name: dev
      activatedBy: [test6-dev]
    - name: eks-dev
      activatedBy: [test6-eks]

deploy:
  kubectl: {}
profiles:
  - name: test6-dev
    activation:
      - kubeContext: kind-gnolive
        env: "GNO_INFRA=test6"
  - name: test6-eks
    activation:
      - kubeContext: arn:aws:eks:eu-central-1:s:cluster/test6-eks-cluster # TODO:
        env: "GNO_INFRA=prod-test6"
    manifests:
      kustomize:
        paths:
        - ./overlays/eks/monitoring-overlays/grafana
        - ./overlays/eks/monitoring-overlays/loki
        - ./overlays/eks/monitoring-overlays/node-exporter
