apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gnocluster
requires:
  # Traefik
  - path: ../../cluster/skaffold/traefik-skaffold.yaml
    activeProfiles: &kubeBaseProfiles
    - name: dev
      activatedBy: [test6-dev]
    - name: eks-dev
      activatedBy: [test6-eks]

  # Gnoland
  - path: ./cluster/skaffold/gnocore-test6-skaffold.yaml
    activeProfiles: &kubeTest6Profiles
    - name: test6-dev
      activatedBy: [test6-dev]
    - name: test6-eks
      activatedBy: [test6-eks]

  - path: ./cluster/skaffold/gnocore-test6-helm-skaffold.yaml
    activeProfiles: *kubeTest6Profiles

  # Monitoring
  - path: ../../cluster/skaffold/monitoring-skaffold.yaml
    activeProfiles: *kubeBaseProfiles

deploy:
  kubectl: {}
profiles:
  - name: test6-dev
    activation:
      - kubeContext: kind-gnolive
        env: "GNO_INFRA=test6"
  - name: test6-eks
    activation:
      - kubeContext: arn:aws:eks:eu-west-3:600627336512:cluster/test6-cluster
        env: "GNO_INFRA=prod-test6"
    manifests:
      kustomize:
        paths:
        - ./overlays/eks/monitoring-overlays/grafana
        - ./overlays/eks/monitoring-overlays/loki
        - ./overlays/eks/monitoring-overlays/node-exporter
