apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../indexer/

patches:
# delete PV definition
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: indexer-pv-volume
      namespace: gno
# add storage class
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: indexer-pv-claim
      namespace: gno
    spec:
      storageClassName: eks-ebs-storage
# fix endpoint ingress
- patch: |- 
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: tx-indexer-ingress
      namespace: gno
    spec:
      routes:
      - match: Host(`indexer.k8s.gnoteam.com`)
        kind: Rule
        services:
        - name: tx-indexer
          namespace: gno
          port: tx-indexer-port
