apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../loki/

patches:
# delete PV definition
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: loki-pv-volume
      namespace: monitoring
# add storage class
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: loki-pv-claim
      namespace: monitoring
    spec:
      storageClassName: eks-ebs-storage
