
app:
  name: gno-val-01
  role: validator

storage:
  capacity: 120Gi
  class: eks-ebs-storage

svc:
  name: gno-val-svc-01

ingress:
  enabled: false

placement:
  tolerations:
    enabled: true
  resources: # saturate resources
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "2"
      memory: "4Gi"
