configMapGenerator:
- name: gno-val-01-config
  namespace: gno
  options:
    disableNameSuffixHash: true
  files:
  - config.toml=config/config.toml
  - node_key.json=secrets/node_key.json
  - priv_validator_key.json=secrets/priv_validator_key.json
  - priv_validator_state.json=secrets/priv_validator_state.json
