
app:
  name: gno-val-01
  role: validator

storage:
  capacity: 200Mi
  local:
    path: /opt/gnoland/validator/1/data

svc:
  name: gno-val-svc-01

ingress:
  enabled: false

placement:
  tolerations:
    enabled: false
