apiVersion: v1
kind: Service
metadata:
  labels:
    gno.service: gnoland
    gno.type: validator
    gno.role: {{ .Values.app.role }}
  name: {{ .Values.svc.name }}
  namespace: {{ default "gno" .Values.app.namespace }}
spec:
  selector:
    gno.service: gnoland
    gno.type: validator
    gno.role: {{ .Values.app.role }}
  clusterIP: None
  type: ClusterIP
  ports:
    - name: rpc-internal
      port: 26656
      targetPort: rpc-internal
