apiVersion: v1
kind: Service
metadata:
  name: traefik
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: traefik
  ports:
  - name: admin
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
  - name: webtls
    protocol: TCP
    port: 443
    targetPort: 443
  - name: p2p
    protocol: TCP
    port: 26656
    targetPort: 26656
  type: LoadBalancer
