apiVersion: v1
kind: Service
metadata:
  name: traefik
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: traefik
  ports:
  - name: admin
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: null
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: null
  - name: webtls
    protocol: TCP
    port: 443
    targetPort: 4443
    # explicitly remove the nodePorts entry to de-allocate those node ports
    nodePort: null
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false # Prevents node port allocation