
app:
  name: gno-sentry-01
  role: validator

storage:
  capacity: 200Mi
  local:
    path: /opt/gnoland/sentry/1/data

svc:
  name: gno-sentry-svc-01

ingress:
  enabled: true
  port: p2p-internal
  rule:
    host: Host(`sentry-01.gnoland.tech`)

placement:
  tolerations:
    enabled: false
