apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploys/tx-indexer-deploy.yaml
- deploys/tx-indexer-svc.yaml
- storage/tx-indexer-pv.yaml
- ingress/tx-indexer-ingress.yaml
