kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: gnoweb-ingress
  namespace: gno
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`web.gnoland.tech`)
    kind: Rule
    services:
    - name: gnoweb
      namespace: gno
      port: gnoweb-port
