apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../gnofaucet/

patches:
# fix endpoint ingress
- patch: |-
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: gnofaucet-ingress
      namespace: gno
    spec:
      entryPoints:
      - web
      routes:
      - match: Host(`gnofaucet.k8s.gnoteam.com`)
        kind: Rule
        services:
        - name: gnofaucet
          namespace: gno
          port: gnofaucet-port
