kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: gnoweb-ingress-tls
  namespace: gno
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gnoweb.test5.gnoteam.com`) || Host(`test5.gno.land`)
    kind: Rule
    services:
    - name: gnoweb
      namespace: gno
      port: gnoweb-port
  tls:
    certResolver: gnoresolver
