apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../overlays/eks/gnoweb/
- gnoweb-tls-ingress-eks.yaml

patches:
- patch: |-
    kind: IngressRoute
    apiVersion: traefik.io/v1alpha1
    metadata:
      name: gnoweb-ingress
      namespace: gno
    spec:
      entryPoints:
        - web
      routes:
      - match: Host(`gnoweb.test5.gnoteam.com`) || Host(`test5.gno.land`)
        kind: Rule
        services:
        - name: gnoweb
          namespace: gno
          port: gnoweb-port


secretGenerator:
- name: gnoweb-env
  namespace: gno
  behavior: replace
  options:
    disableNameSuffixHash: true
  envs:
    - secrets/test5.eks.gnoweb.ini
