---
apiVersion: v1
kind: Service
metadata:
  name: vector-headless
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Agent
spec:
  selector:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Agent
  clusterIP: None
  type: ClusterIP
  ports:
    - name: syslog
      port: 9000
      protocol: TCP
    - name: vector
      port: 6000
      protocol: TCP
    - name: prom-exporter
      port: 9090
      protocol: TCP
