apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../../monitoring/vector/

patches:
- patch: |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: vector
      namespace: monitoring
    spec:
      template:
        spec:
          tolerations:
          - key: "type"
            operator: "Equal"
            value: "validator"
            effect: "NoSchedule"
