{
 "title": "Container monitoring",
 "description": "Overview of Containers in Kubernetes Cluster",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aws_eks_hostanme_node_group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".+\", container!=\"\",  namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"}[$interval])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\".+\", container!=\"\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\".+\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\".+\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\".+\", container!=\"\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"} > 0 ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\".+\", container!=\"\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"}) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum( (((container_spec_memory_limit_bytes{pod=~\".+\", container!=\"\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"} > 0) - container_memory_usage_bytes{pod=~\".+\", container!=\"\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"}) * 100) / (container_spec_memory_limit_bytes{pod=~\".+\", container!=\"\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"} > 0)) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{pod=~\".+\", container!=\"\", namespace=~\"$namespace\", aws_eks_hostanme_node_group=~\"$instance\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}