{
 "title": "Validators Logs",
 "tags": [
  "logs",
  "gnologs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "validator_pod_name",
    "label": "Validator Pod",
    "query": {}
   },
   {
    "name": "non_validator_pod_name",
    "label": "Non-Validator Pod",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Gno validators Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{logsource=\"kube\"} | json  | line_format \"{{ .kubernetes_pod_name }} - {{ .message }}\" | kubernetes_pod_namespace=`gno`, kubernetes_pod_labels_gno_service=`gnoland`, kubernetes_pod_labels_gno_name=`$validator_pod_name`"
    }
   ]
  },
  {
   "title": "Amount of Logs - Gno Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (count_over_time( { logsource=\"kube\" } | json  | line_format \" {{ .message }}\" | kubernetes_pod_namespace=`gno`, kubernetes_pod_labels_gno_service=`gnoland` [$__interval]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Gno Logs (non validators)",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{logsource=\"kube\"} | json  | line_format \"{{ .kubernetes_pod_name }} - {{ .message }}\" | kubernetes_pod_namespace=`gno`, kubernetes_pod_labels_gno_service=`$non_validator_pod_name` "
    }
   ]
  }
 ]
}