# Gnoland Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gno-pv-volume
  namespace: gno
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/gnoland/data" 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnoland-pv-claim
  namespace: gno
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
