apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-indexer
  namespace: gno
spec:
  replicas: 1
  selector:
    matchLabels:
      gno.service: tx-indexer
  template:
    metadata:
      labels:
        gno.service: tx-indexer
    spec:
      containers:
      - name: tx-indexer
        image: ghcr.io/gnolang/tx-indexer:0.5.2
        imagePullPolicy: IfNotPresent
        args:
          - start
          - -http-rate-limit=500
          - -max-slots=2000
          - -listen-address=0.0.0.0:8546
          - -remote=http://gnoland-rpc:26657
          - -db-path=/opt/indexer-db
        volumeMounts:
        - name: indexer-vol
          mountPath: /opt/indexer-db
        ports:
          - containerPort: 8546
      volumes:
      - name: indexer-vol
        persistentVolumeClaim:
          claimName: indexer-pv-claim
