apiVersion: v1
kind: Service
metadata:
  labels:
    gno.service: tx-indexer
  name: tx-indexer
  namespace: gno
spec:
  selector:
    gno.service: tx-indexer
  ports:
  - name: tx-indexer-port
    port: 8546
    targetPort: 8546
    protocol: TCP

