kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: gnofaucet-ingress
  namespace: gno
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`faucet.gnoland.tech`)
    kind: Rule
    services:
    - name: gnofaucet
      namespace: gno
      port: gnofaucet-port
