apiVersion: v1
kind: Service
metadata:
  labels:
    gno.service: gnoland
    gno.type: validator
    gno.role: validator
  name: gnoland-val
  namespace: gno
spec:
  selector:
    gno.service: gnoland
    gno.type: validator
    gno.role: validator
  clusterIP: None
  type: ClusterIP
  ports:
    - name: rpc-internal
      port: 26656
      targetPort: rpc-internal
