apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    gno.service: gnoland
    gno.type: validator
  name: gnoland-validator
  namespace: gno
spec:
  replicas: 1
  selector:
    matchLabels:
      gno.service: gnoland
      gno.type: validator
  template:
    metadata:
      labels:
        gno.service: gnoland
        gno.type: validator
        gno.role: validator
    spec:
      initContainers:
      - name: init-genesis-secrets
        # copies files from configmap into PVC to avoid RO fs problems
        image: busybox
        command:
        - sh
        - -c
        - |
          cp /gnoroot/genesis/genesis.json /gnoroot/gnoland-data/genesis.json
          cp -r /gnoroot/secrets /gnoroot/gnoland-data/secrets
        volumeMounts:
        - name: gno-val-vol
          mountPath: /gnoroot/gnoland-data
        - name: gno-val-secrets
          mountPath: /gnoroot/secrets
        - name: gnoland-genesis
          mountPath: /gnoroot/genesis
      - name: init-genesis-txs
        image: ghcr.io/gnolang/gno/gnocontribs:master
        command:
        - gnogenesis
        - txs
        - add
        - packages
        - /gnoroot/examples
        - -genesis-path
        - /gnoroot/gnoland-data/genesis.json
        volumeMounts:
        - name: gno-val-vol
          mountPath: /gnoroot/gnoland-data
      - name: init-genesis-balance
        image: ghcr.io/gnolang/gno/gnocontribs:master
        command:
        - gnogenesis
        - balances
        - add
        - -balance-sheet
        - /gnoroot/gno.land/genesis/genesis_balances.txt
        - -genesis-path
        - /gnoroot/gnoland-data/genesis.json
        volumeMounts:
        - name: gno-val-vol
          mountPath: /gnoroot/gnoland-data
      containers:
      - name: gnoland
        image: ghcr.io/gnolang/gno/gnoland:master
        imagePullPolicy: IfNotPresent
        args:
          - start
          - -genesis=/gnoroot/gnoland-data/genesis.json # loaded from init container
        ports:
          - name: val-internal
            containerPort: 26656
        resources:
          limits:
            cpu: "1000m"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "2Gi"
        volumeMounts:
        - name: gno-val-vol
          mountPath: /gnoroot/gnoland-data
        - name: gno-val-conf
          mountPath: /gnoroot/gnoland-data/config
      volumes:
      - name: gno-val-vol
        persistentVolumeClaim:
          claimName: gno-val-pv-claim
      - name: gno-val-conf
        configMap:
          name: gno-val-config
          items:
          - key: config.toml
            path: config.toml
      - name: gno-val-secrets
        configMap:
          name: gno-val-config
          items:
          - key: node_key.json
            path: node_key.json
          - key: priv_validator_key.json
            path: priv_validator_key.json
          - key: priv_validator_state.json
            path: priv_validator_state.json
          - key: node_key.json
            path: node_key.json
      - name: gnoland-genesis
        configMap:
          name: gno-genesis
          items:
          - key: genesis.json
            path: genesis.json
