apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../jobs/snapshots/

secretGenerator:
- name: snapshotter-env
  namespace: gno
  behavior: merge
  options:
    disableNameSuffixHash: true
  envs:
    - secrets/.env
