
app:
  name: gno-val-06
  role: validator

storage:
  capacity: 200Mi
  local:
    path: /opt/gnoland/validator/6/data

svc:
  name: gno-val-svc-06

ingress:
  enabled: false

placement:
  tolerations:
    enabled: false
