apiVersion: v1
kind: Service
metadata:
  labels:
    gno.service: gnofaucet
  name: gnofaucet
  namespace: gno
spec:
  selector:
    gno.service: gnofaucet
  ports:
  - name: gnofaucet-port
    port: 5050
    targetPort: 5050
    protocol: TCP
