apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../jobs/supernova/

secretGenerator:
- name: supernova-env
  namespace: gno
  behavior: merge
  options:
    disableNameSuffixHash: true
  envs:
    - secrets/.env
