apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../grafana/

patches:
# delete PV definition
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: grafana-pv-volume
      namespace: monitoring
# add storage class
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: grafana-pv-claim
      namespace: monitoring
    spec:
      storageClassName: eks-ebs-storage
# fix endpoint ingress
- patch: |- 
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: grafana-ingress
      namespace: monitoring
    spec:
      routes:
      - match: Host(`grafana.k8s.gnoteam.com`)
        kind: Rule
        services:
        - name: grafana
          namespace: monitoring
          port: grafana-port
