kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`grafana.gnoland.tech`)
    kind: Rule
    services:
    - name: grafana
      namespace: monitoring
      port: grafana-port
