apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../gnoland/rpc/

patches:
# delete PV definition
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: gno-rpc-pv-volume
      namespace: gno
# add storage class
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: gno-rpc-pv-claim
      namespace: gno
    spec:
      storageClassName: eks-ebs-storage
# remove middleware
- patch: |-
    $patch: delete
    kind: Middleware
    apiVersion: traefik.io/v1alpha1
    metadata:
      name: gno-stripprefix
      namespace: gno
# fix endpoint ingress
- path: gnoland-ingress-eks.yaml
