x-logging: &logging
  driver: "json-file"
  options:
    max-file: "10"
    max-size: "100m"

# https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
services:
  gnobro:
    build: .
    # image: ghcr.io/gnolang/gno/gnobro:master
    command:
      - "-remote=rpc.test4.gno.land:80"
      - "-chainid=test4"
      - "-ssh=0.0.0.0:22"
      - "-banner"
    user: gno
    ports:
      - 8022:22
    tty: true
    # stdin_open: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
    volumes:
      - "./gnobro-data/:/gnoroot/.ssh"
    networks:
      - gnobro
    restart: on-failure
    logging: *logging

networks:
  gnobro: {}
