apiVersion: v1
kind: Service
metadata:
  name: loki-svc
  namespace: monitoring
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3100
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 3100
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 3100
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        volumeMounts:
        - name: loki-vol
          mountPath: /data
        - name: config
          mountPath: /etc/loki
      volumes:
      - name: loki-vol
        persistentVolumeClaim:
          claimName: loki-pv-claim
      - name: config
        configMap:
          name: loki-conf
          items:
          - key: loki.yaml
            path: local-config.yaml